// <auto-generated />
using System;
using EvidencijaVozila.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidencijaVozila.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707071502_OsigurajJedanAktivanNalogPoVozilu")]
    partial class OsigurajJedanAktivanNalogPoVozilu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidencijaVozila.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.HasIndex("SectorId");

                    b.HasIndex("ServiceDepartmentId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.OrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationalUnits");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrganizationalUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.ServiceDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("ServiceDepartments");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandModel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("int");

                    b.Property<string>("CurrentTires")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TireChangeNote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.VehicleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBusinessTrip")
                        .HasColumnType("bit");

                    b.Property<int?>("MileageAfter")
                        .HasColumnType("int");

                    b.Property<int>("MileageBefore")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrganizationalUnitId");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleOrders_ActiveVehicle")
                        .HasFilter("[Status] = 1");

                    b.ToTable("VehicleOrders");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.AppUser", b =>
                {
                    b.HasOne("EvidencijaVozila.Models.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidencijaVozila.Models.Sector", "Sector")
                        .WithMany("Users")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidencijaVozila.Models.ServiceDepartment", "ServiceDepartment")
                        .WithMany("Users")
                        .HasForeignKey("ServiceDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("Sector");

                    b.Navigation("ServiceDepartment");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.Sector", b =>
                {
                    b.HasOne("EvidencijaVozila.Models.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Sectors")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.ServiceDepartment", b =>
                {
                    b.HasOne("EvidencijaVozila.Models.Sector", "Sector")
                        .WithMany("ServiceDepartments")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.VehicleOrder", b =>
                {
                    b.HasOne("EvidencijaVozila.Models.AppUser", "CreatedByUser")
                        .WithMany("CreatedOrders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidencijaVozila.Models.AppUser", "Driver")
                        .WithMany("DrivenOrders")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidencijaVozila.Models.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Orders")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidencijaVozila.Models.Vehicle", "Vehicle")
                        .WithMany("Orders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Driver");

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.AppUser", b =>
                {
                    b.Navigation("CreatedOrders");

                    b.Navigation("DrivenOrders");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.OrganizationalUnit", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sectors");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.Sector", b =>
                {
                    b.Navigation("ServiceDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.ServiceDepartment", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EvidencijaVozila.Models.Vehicle", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
